deploy-frontend:
  stage: deploy
  tags:
    - ec2-runner
  dependencies:
    - build-frontend
  before_script:
    - echo "====== [Deploy-FE] 배포 환경을 준비합니다. (패키지 설치 및 SSH 설정) ======"
    - apk update && apk add openssh-client rsync
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $LIVE_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - echo "====== [Deploy-FE] 프론트엔드 파일 배포 시작 ======"
    - rsync -avz --delete ./FrontEnd/dist/ ubuntu@$LIVE_SERVER_IP:/var/www/html/
    - echo "✅ [Deploy-FE] 프론트엔드 파일 배포 완료"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - FrontEnd/**/*
