upstream blue {
    server 43.201.97.186:8080;
}
upstream green {
    server 43.201.97.186:8081;
}

server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    include /etc/nginx/conf.d/service-env.inc;

    # ============================
    # 프론트엔드(Vue 정적 파일)
    # ============================
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # ============================
    # 백엔드 API (Blue/Green 프록시)
    # ============================
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://$service_url;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
