spring:
  application:
    name: NareuGO_Backend

  profiles:
    active: local
    group:
      local: local,common
      blue: blue,common
      green: green,common

# 공통 설정
---
spring:
  config:
    activate:
      on-profile: common
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: org.example.nareugobackend
  configuration:
    map-underscore-to-camel-case: true

# ===========================================
# 토스페이먼츠 결제 API 설정
# ===========================================
# 토스페이먼츠 API 연동을 위한 설정값들
# - secret-key: 토스페이먼츠에서 발급받은 시크릿 키 (환경 변수로 주입)
# - confirm-url: 토스페이먼츠 결제 승인 API 엔드포인트
payments:
  toss:
    secret-key: ${TOSS_SECRET_KEY} # 환경 변수로 시크릿 키 주입
    confirm-url: https://api.tosspayments.com/v1/payments/confirm

# Local 환경
---
spring:
  config:
    activate:
      on-profile: local

server:
  port: ${SERVER_PORT_LOCAL}
  serverAddress: ${SERVER_ADDRESS_LOCAL}
  env: local

serverName: local_server

# Blue 환경
---
spring:
  config:
    activate:
      on-profile: blue

server:
  port: ${SERVER_PORT_BLUE}
  serverAddress: ${SERVER_ADDRESS_BLUE}
  env: blue

serverName: blue_server

# Green 환경
---
spring:
  config:
    activate:
      on-profile: green

server:
  port: ${SERVER_PORT_GREEN}
  serverAddress: ${SERVER_ADDRESS_GREEN}
  env: green

serverName: green_server
