# ROS2 로봇 통신 설정
ros:
  robot:
    # ROS2 HTTP 서버 설정
    http-server:
      host: localhost
      port: 8888
      timeout: 5000
      connection-pool-size: 10

    # 로봇 상태 확인 설정
    status:
      check-interval: 10000  # 10초마다 상태 확인
      connection-timeout: 30000  # 30초 연결 타임아웃
      retry-attempts: 3

    # 지원하는 로봇 목록
    supported-robots:
      - id: "1"
        name: "NareuGO"
        type: "turtlebot3"
      - id: "2"
        name: "NareuGO2"
        type: "turtlebot3"

# WebClient 설정 (ROS2 서버와 통신용)
spring:
  webflux:
    webclient:
      connect-timeout: 5000
      read-timeout: 10000
      write-timeout: 10000