# 최소 구성 예시: goal 판정 완화 + 회전/후진 억제
controller_server:
  ros__parameters:
    use_realtime_priority: true

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.08      # 0.08~0.10 권장
      yaw_goal_tolerance: 0.35     # 최종 회전 집착 감소
      stateful: True               # 한 번 성공하면 재시도하지 않음

    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      allow_reversing: false       # 후진 금지(왕복 억제)
      use_rotate_to_heading: false # 목표 전 회전 단계 제거
      min_x_velocity_threshold: 0.05
      min_theta_velocity_threshold: 0.05
      desired_linear_vel: 0.30
      max_linear_accel: 0.5
      max_angular_accel: 1.2
      lookahead_dist: 0.55
      min_lookahead_dist: 0.35
      max_lookahead_dist: 0.90
      regulate_max_speed: true
      approach_velocity_scaling: true

local_costmap:
  local_costmap:
    ros__parameters:
      inflation_layer:
        inflation_radius: 0.30
        cost_scaling_factor: 4.0
      obstacle_layer:
        observation_persistence: 0.05  # 문 열림으로 코스트 급변 완화
